### ISSUE TITLE
Mongodb?

### ISSUE THREAD

**Issue by idkjs** [reactql/kit#103]
I feel like i remember an early version of this using mongodb. Is there an example using that? 

Great project. The documentation really helps to understand what is going on. Thanks!

Thank you.

**Comment by leebenson** [comment]
Maybe you're thinking of [Meteor](https://www.meteor.com/)?

The closest we've got is https://github.com/reactql/example-auth, which uses an in-memory SQLite database to demonstrate one way you might implement user auth.

Of course, you're totally free to use whichever database makes sense to you on the back-end, in any way you want-- ReactQL doesn't restrict you.
