### ISSUE TITLE
ES6 -> Typescript

### ISSUE THREAD

**Issue by leebenson** [reactql/kit#110]
A while back, we had a community-supposed [Typescript version](https://github.com/reactql/kit.ts) of the kit. This was deprecated as a result of version slippage against the ES6 kit, but provided a great way enjoy a mostly 'type safe' ReactQL experience.

Since the last commit in August, ReactQL has gone through several major iterations, including the addition of a built-in GraphQL server and a `Config` class that keeps most customisation in userland. This has expanded the surface area of ReactQL, whilst introducing many new (presently undocumented) functions and features.

It now makes sense to make Typescript the de facto (and indeed, only) version of ReactQL. IMO, this would significantly improve the experience of working with undocumented config features, and eliminate typo-induced edge cases that are difficult to catch until they become a problem at runtime.

I want to introduce TS is a mostly seamless way; the kit itself would be written in Typescript, and you'll be able to create `.ts` files inside `src` where you'd normally write plain JS. At the same time, if you want to continue to write ES6 `.js`, just do what you're already doing - and it should just work.

This should land in ReactQL kit v3.0.

**Comment by tzarger** [comment]
@leebenson This is great news for TS users. Do you have an ETA for v3.0 Kit?

**Comment by leebenson** [comment]
@tzarger - I'll be starting on the conversion somewhere around mid-Nov. Need to get a couple of local project deadlines out the way, then I'm on it. It's high priority on my to-do, so this will be the next major feature tackled.

**Comment by nate0001** [comment]
From what I've seen, a lot of the React 16 and Apollo 2.0 types are severely broken right now.

**Comment by leebenson** [comment]
@nate0001 - could you elaborate?

**Comment by nate0001** [comment]
https://github.com/apollographql/react-apollo/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20typescript for example

**Comment by leebenson** [comment]
I guess I've got that to look forward to as I start converting...

**Comment by tzarger** [comment]
@leebenson How's this coming along? Any updated info v3 coming up?

**Comment by leebenson** [comment]
Getting close to releasing something. We have a newborn in the house, so my schedule has been somewhat skewed/unpredictable lately. I'm hoping to carve out a bit of time in the coming week to get a working demo committed. Will keep you posted.

**Comment by tzarger** [comment]
Awesome @leebenson and congrats on the newborn!

**Comment by Baza58** [comment]
@leebenson How's the demo coming along?

**Comment by corydeppen** [comment]
@leebenson Would you recommend against trying to migrate a new ReactQL project to TS until you're changes are released, assuming there will be some sort of upgrade path?

Just curious - are you considering using the [Babel preset for TypeScript](https://github.com/babel/babel/tree/master/packages/babel-preset-typescript) so you can continue using babel-loader without needing another loader for TS?

**Comment by leebenson** [comment]
I'd recommend doing whatever makes sense for your project. If you need TS support today, don't wait for an upgrade- add it, and get coding!

If/when TS support lands, it's likely the whole kit will get an overhaul, including the Webpack config files. It'll likely be some combo of ts-loader and HappyPack.

**Comment by leebenson** [comment]
Update on this thread: https://github.com/reactql/kit/issues/147#issuecomment-378173217

**Comment by leebenson** [comment]
Typescript - done!

https://github.com/leebenson/reactql/releases/tag/3.0.0
