### ISSUE TITLE
Docker container fails with node:alpine when calling bcrypt

### ISSUE THREAD

**Issue by arsanjea** [reactql/kit#114]
Known node:alpine bug on Google App Engine - I get a segmentation fault with a node server restart after calling:
`bcrypt.hash("abc@abc.com", 10)`

Adding the following towards the end of Dockerfile fixes the issue (requires ephemeral packages to be kept until the following operation is completed).
`RUN npm rebuild bcrypt --build-from-source`

**Comment by kane-c** [comment]
The Dockerfile is only a starting point. You will need to modify it for your own app's dependencies, especially if they require compilation.

**Comment by kane-c** [comment]
What if you modify the Dockerfile like this?

```
# Install everything (and clean up afterwards)
RUN apk add --no-cache --virtual .gyp \
    autoconf \
    automake \
    g++ \
    libpng-dev \
    libtool \
    make \
    nasm \
    python \
    git \
  && npm i \
  && npm rebuild bcrypt --build-from-source \
  && apk del .gyp
```

See also: https://github.com/kelektiv/node.bcrypt.js/issues/528#issuecomment-329975006

**Comment by leebenson** [comment]
You can also use the general `npm rebuild --build-from-source` which should re-build _every_ binary, in case you run into this error with third-party packages.

I'll go ahead and close this since this doesn't directly impact a fresh ReactQL build, and is dependent on what is added to the project later.

**Comment by arsanjea** [comment]
Per the other issue, that's what I ended up doing.

*-------------------------------------*
*Jean-Marc Arsan*
Founder & CTO @ MoneyGoat <https://www.goat.money/>
79 Madison Avenue, Suite 55
<https://maps.google.com/?q=79+Madison+Avenue,+Suite+55New+York,+NY,+10016&entry=gmail&source=g>
New York, NY, 10016
<https://maps.google.com/?q=79+Madison+Avenue,+Suite+55New+York,+NY,+10016&entry=gmail&source=g>

phone: +1 (310) 435-9983
email: jm@Goat.Money
