### ISSUE TITLE
Polyfills

### ISSUE THREAD

**Issue by flopes89** [reactql/kit#116]
First off: Awesome project, I'm really loving it. However, as I played around with it and opened it in IE11, it didn't work, so I dug around a bit, and found that despite the README says

> Dynamic polyfills, courtesy of babel-preset-env

no actual (in my mind) polyfills were being used. When I think about polyfills, I would expect to find a `babel-polyfill` for things like `Object.assign` (that are used in this kit) somewhere.

Am I missing something important or is this just a minor oversight? Is there a problem with adding those polyfills to target "all" browers?

**Comment by klarstrup** [comment]
I too noticed this was not enabled by default, gotta add `useBuiltIns: "usage"` to babel-preset-env settings. Maybe a PR is in order.

**Comment by leebenson** [comment]
TBH, ReactQL could do with more testing in older browsers. Would certainly accept PRs.

**Comment by klarstrup** [comment]
An overhaul of the babel deps and config might be due once Babel 7 comes out one of these days, too.

**Comment by flopes89** [comment]
I opened a PR for this, #119 - further discussion there I guess?

**Comment by leebenson** [comment]
Apologies for the generic response, but I've released a new [v3.0 kit](https://github.com/leebenson/reactql/releases/tag/3.0.0), which has been re-written from the ground up.

It bumps the ReactQL stack to Webpack 4, React 16.4, Apollo Client 2.0, and adds Styled Components, full SSR (even in development), and has been re-written in Typescript. It's leaner, faster and has been brought completely up-to-date.

If you're still using ReactQL (and I appreciate you may not be, given the time lag in my response), I'd recommend checking out the new kit to see if your issue has been answered. If not, please feel free to post a new issue at https://github.com/leebenson/reactql
