### ISSUE TITLE
Is it possible to deploy static sites as docker containers?

### ISSUE THREAD

**Issue by fqlx** [reactql/kit#120]
I see we can deploy static + server as a container, but what if I only want to deploy static files?

Great project by the way!

**Comment by leebenson** [comment]
Sure. But you'll need a web server to actually serve up the files-- Nginx, Apache, etc. Setting that up is beyond the scope of ReactQL, unless you use the built-in web server that's designed to serve React requests. Try stackoverflow.com for help.

**Comment by fqlx** [comment]
Thanks Lee!
