### ISSUE TITLE
SSR rehydration breaks when certain characters are present.

### ISSUE THREAD

**Issue by klarstrup** [reactql/kit#121]
(Probably the title could be better)

Steps to reproduce:
1. Check out a fresh kit & `npm install`
2. Change ```config.addReducer('counter', counterReducer, { count: 0 });``` in app.js to ```config.addReducer('counter', counterReducer, { count: 0, bogus: ` ` });```(there is a U+2028 character in the bogus key's string value)
3. `npm run start`
4. Navigate to `localhost:8081`
5. Observe failure to rehydrate and syntax error message in the console.

A PR with a fix will follow shortly

**Comment by leebenson** [comment]
Apologies for the generic response, but I've released a new [v3.0 kit](https://github.com/leebenson/reactql/releases/tag/3.0.0), which has been re-written from the ground up.

It bumps the ReactQL stack to Webpack 4, React 16.4, Apollo Client 2.0, and adds Styled Components, full SSR (even in development), and has been re-written in Typescript. It's leaner, faster and has been brought completely up-to-date.

If you're still using ReactQL (and I appreciate you may not be, given the time lag in my response), I'd recommend checking out the new kit to see if your issue has been answered. If not, please feel free to post a new issue at https://github.com/leebenson/reactql
