### ISSUE TITLE
app.js config / middleware does not work in development mode

### ISSUE THREAD

**Issue by noeljackson** [reactql/kit#125]
Conditional SERVER specified routes and middleware from custom `config` from app.js does not work in development mode.

For example, the `/test/` route in a fresh `reactql` app, only works if the app is started with `npm run start` not `npm run build && npm run server`.

`/test` on a dev server just navigates to /test
`/test` on a production server renders `/test` with a custom message.

Any idea how we can utilize koa (and other) middleware **and** test it in development? Not just in production?

**Comment by leebenson** [comment]
@noeljackson - it should be working on port `:8081` in development... is that not the case?

**Comment by noeljackson** [comment]
True, the routes work on `:8081`, but you run into issues on the SSR where any access to window in your templates results in `window is not defined` and then the page doesn't load. I realize you can use if(SERVER) in templates, but this results in some pretty strange conditional statements. 

Any way we could implement koa routes and middleware and have them accessible during development? I am stumped, but it has to be possible.

**Comment by leebenson** [comment]
If I understand what you're asking for - that's unfortunately not possible.

Koa is a Node.js-only library that uses the built-in `http` package to listen on a TCP port, and respond to requests. There's nothing equivalent that exists in the browser, so it wouldn't be possible to simply write Koa middleware and expect that it'd work in on the client-side. In the same way you wouldn't be able to use a database or call a local file in the browser-- the server's IO doesn't exist.

Routing on the browser is a bit of a trick - it's not really a 'web server', but merely looking at the location bar of the browser and rendering the appropriate UI against the DOM. That's in contrast to Koa on the server, which is 'physically' listening to a HTTP port, interpreting headers, and sending packets down the wire, back to the browser. Two very different environments, doing different things.

As far as `window` not being available on the server, the same works in reverse -- where server IO isn't available in the browser, the browser's DOM isn't available on the server. You need to write React components and consume third-party libs in a way that `window` access isn't being attempted on the server... e.g. by putting import statements inside of `componentDidMount()`, checking in `if (SERVER)` blocks, or using browser-only or server-only code in 'safe' ways where you can guarantee those functions are only executed in the required environment.
