### ISSUE TITLE
Can't Get Data from GraphQL when Changing to Other Page

### ISSUE THREAD

**Issue by nwicakson** [reactql/kit#127]
I already deployed my project using reactql at http://beta.if.its.ac.id.
The problem is it can't get the data from graphql when changing to other page. But when I reload the other page, it will get the data.

Reproduce:
1. Codes: https://github.com/nwicakson/informatics-reactql
2. Install as my explanations there
3. npm start
4. Access with other device in [your network]:8081
5. The problem will occur when changing page

**Comment by nwicakson** [comment]
![image](https://user-images.githubusercontent.com/13409319/33795545-3e221f12-dd16-11e7-82a5-cc50941eb4bd.png)
It seems like it's because the graphql url is wrong. How can I change that url?

**Comment by leebenson** [comment]
```js
config.setGraphQLEndpoint('https://host/path/to/graphql');
```

**Comment by nwicakson** [comment]
Wait, I used the internal GraphQL server beta.if.its.ac.id/graphql. How can I get the data from it?

**Comment by nwicakson** [comment]
#92 Actually, it's the same problem as this issue. Thank you for your time
