### ISSUE TITLE
Unable to generate build & Expected server html error on server side dev

### ISSUE THREAD

**Issue by haxxorsid** [reactql/kit#130]
What's the solution for:
**Expected server HTML to contain a matching div in div.**

I fixed this for browser side by reading solution mentioned in reactql cli's Issue No. 86. That is:
```
function doRender() {
  const main = document.getElementById('main');
  const renderOrHydrate = main.innerHTML.trim().length ? 'hydrate' : 'render';
  ReactDOM[renderOrHydrate](
    <Root />,
    main,
  );
}
```
But I'm receiving this error in server side too, when I access some page other than "/" directly and also css somewhat gets disrupt. For few miliseconds it shows homepage and later it turns up to the page which I needed, but that remains to be disrupted.

Next problem is when I run:
`npm run build`

I received this error:
```
Error: browser_prod.js not found or has errors:
{ Error: Cannot find module 'chunk-manifest-webpack-plugin'
```
So I did: `npm install chunk-manifest-webpack-plugin`

Then tried run build and errors while run build:
```
warning: couldn't load iltorb library. trying to fall back to brotli.
{ Error: Cannot find module './build/bindings/iltorb.node'
```
Then more:
```
 ERROR in ./src/styles.global.css
    Module build failed: ModuleBuildError: Module build failed: Error: The system cannot find the path specified.
```

**Comment by leebenson** [comment]
Run `npm rebuild`

**Comment by reduxdj** [comment]
I love your framework, I wish we would have chosen something different. Unfortunately, we built 4 projects with it, and now it's showing its age, installation issues... build failures, dependency issues. I was excited, but now i think we've shot ourselves in the foot a bit.

**Comment by reduxdj** [comment]
removing these compressor plugins is the safest course of action for ubuntu. They stopped compiling and don't fall back correctly.
