### ISSUE TITLE
Add media folder in layout

### ISSUE THREAD

**Issue by haxxorsid** [reactql/kit#134]
I want to create a separate media folder where users will upload images and that will be utilized to show stuff like article's content. Where am I supposed to make changes?

**Comment by leebenson** [comment]
Anywhere. You can import images like:

```js
import someImage from 'src/images/whatever.jpg';
```

... and it'll automatically be minified, compressed and moved to `dist/public`

**Comment by haxxorsid** [comment]
@leebenson Where can I add a custom nodejs route for both prod and dev ? Is it only `kit/lib/server_dev.js` & `server_prod.js`?
