### ISSUE TITLE
Module parse failed: Unexpected character '�' (1:2) You may need an appropriate loader....

### ISSUE THREAD

**Issue by haxxorsid** [reactql/kit#135]
I added sharp package. But I am not able to utilize it:

```
(undefined) ./node_modules/sharp/build/Release/sharp.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/sharp/lib/constructor.js 9:14-52
 @ ./node_modules/sharp/lib/index.js
 @ ./kit/lib/sharp.js
 @ ./src/app.js
 @ ./kit/entry/browser.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080/ webpack/hot/only-dev-server ./kit/entry/browser.js
```

What's the possible fix for this? I googled and got 1-2 answers for this, but I'm not aware of where and how correct changes should be made in reactql's existing webpack config.

**Comment by leebenson** [comment]
You'll need to use this solely on the server, since it's a Node binary. Looking at your stack trace, it seems that you're trying to use it in `src/app.js`, which is loaded by `kit/entry/browser`.

To use it in a 'safe' server-only block, wrap it in:

```js
if (SERVER) {
  // stuff you want to only want to `require` / run on the server
}
```

**Comment by haxxorsid** [comment]
@leebenson Ok thanks. How can I fix the linting issue: 

> ESLint: Promise is not supported in Opera Mobile 12, Opera Mini all, IE Mobile 10, IE 9, Blackberry Browser 7 (compat/compat)

I am using promise for implementing sharp. Should I add a polyfill?

**Comment by leebenson** [comment]
I'm not familiar with Sharp, and can't offer any specific advice on implementing non-ReactQL parts of your stack. Questions are better suited for [stackoverflow.com](https://stackoverflow.com) - this issue board is for reporting bugs / discussing features of ReactQL specifically.

**Comment by Heveraldoo** [comment]
The same problem with opencv4nodejs.


[ng] WARNING in ./node_modules/opencv4nodejs/lib/cv.js 15:7-68
[ng] Critical dependency: the request of a dependency is an expression
[ng] WARNING in ./node_modules/opencv4nodejs/lib/cv.js 17:7-70
[ng] Critical dependency: the request of a dependency is an expression
[ng]
[ng] ERROR in ./node_modules/opencv4nodejs/build/Release/opencv4nodejs.node 1:2
[ng] Module parse failed: Unexpected character '�' (1:2)
[ng] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[ng] (Source code omitted for this binary file)

**Comment by leebenson** [comment]
@Heveraldoo - did you try the advice [in this comment](https://github.com/reactql/kit/issues/135#issuecomment-353077505)?

It sounds like you might need to forego using this as a top-level `import` and instead use a conditional `require` or async `import` inside an `if SERVER {..}` block.

**Comment by Heveraldoo** [comment]
I'm developing an ionic app in typescript:

import { Component } from '@angular/core';
import * as cv from 'opencv4nodejs';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  constructor() {}
  teste(){
     var imageMAT = cv.imread("teste.jpg"); 
  }
}

So, I means SERVER not exist.

**Comment by leebenson** [comment]
This is a very old repo - ReactQL has moved to https://github.com/leebenson/reactql

ReactQL is built for React -- if you're trying to use Angular with it, this isn't the right starter kit for your project.
