### ISSUE TITLE
Webpack dev server dependency breaks reactql in dev mode

### ISSUE THREAD

**Issue by myovchev** [reactql/kit#138]
There is a (very) recent issue with webpack-dev-server (versions after 2.9.7) which results in non-working browser webpack server after updating dependencies (both yarn and npm). 

**Temporary solution:** downgrade to webpack-dev-server v2.9.7
`npm install --save-dev webpack-dev-server@2.9.7`

or

`yarn add -D webpack-dev-server@2.9.7`

**Long-term solution:** Force webpack version to 2.CURRENT_ISSUE_PATCH_VERSION+ when released (reading dev comments, I'm assuming it will be out soon).

Detailed issue description is on [Webpack issue trakcer](https://github.com/webpack/webpack-dev-server/issues/1259)

**Comment by leebenson** [comment]
Apologies for the generic response, but I've released a new [v3.0 kit](https://github.com/leebenson/reactql/releases/tag/3.0.0), which has been re-written from the ground up.

It bumps the ReactQL stack to Webpack 4, React 16.4, Apollo Client 2.0, and adds Styled Components, full SSR (even in development), and has been re-written in Typescript. It's leaner, faster and has been brought completely up-to-date.

If you're still using ReactQL (and I appreciate you may not be, given the time lag in my response), I'd recommend checking out the new kit to see if your issue has been answered. If not, please feel free to post a new issue at https://github.com/leebenson/reactql

**Comment by myovchev** [comment]
@leebenson I'm using adapted version of reactql & kit, all of those are in production and I'm pretty happy with them. In fact it's pretty close to what you have done with v3. I've just read the announcement and had quick view on the README doc and I'm really impressed - congrats for the great work :)

I'll definitely give it a try. I'll give my best to find time and share with you some of the improvements I made in the past in case you are interested.
Cheers!

**Comment by leebenson** [comment]
Awesome @myovchev, would very much appreciate any contributions!
