### ISSUE TITLE
Could you please provide an example of component code splitting

### ISSUE THREAD

**Issue by mairh** [reactql/kit#14]
So far the starter kit works great. However, could you please provide an example of the react component code splitting (i.e creating different folder/components). At the moment everything is under `src` folder. How does react router 4 works with react component resides in the different folder under `src`.

**Comment by leebenson** [comment]
You can organise folders however you like. When you import anything, it will search from the project root upwards. So you might import other components like this:

```js
import Button from 'src/forms/button.js';
import css from 'src/styles/page.css';
import ImageIcon from 'src/icons/svg/someImage.svg';
```

You can even put stuff outside out of `src` if you like -- although as a convention, keeping everything within that folder makes it easy to know what's 'your' code and what's the kit.

React Router 4 doesn't care where your components are stored. There's no relationship between routes and paths to components. You just import them at the top-level of your Javascript and use the variable name in React Router to reference what should be displayed given a specific route.

Does that answer your question?

**Comment by mairh** [comment]
Thanks. I will try that out. Meanwhile closing this issue.
