### ISSUE TITLE
set initial state from localstorage

### ISSUE THREAD

**Issue by filtudo** [reactql/kit#142]
Hello,

I am struggling a bit in re-populating a store from localStorage(we use micro services and the data is passed from one app to another in localStorage ).

I looked at the examples here : https://github.com/reactql/example-auth but in my case unfortunately i can't use cookies. 

- I tried to call an action on componentWillMount() in the main component
- I tried to change the initial state based on a if statement on SERVER global var
- i tried to add the dispatch event in the entry/browser.js before the store variable is injected

But all are either ignored or i get message that the server side html is not valid.

I would really appreciate if anyone could point me in the right direction.

Cheers

**Comment by akshitggrwl** [comment]
> dd the dispatch event in the entry/browser.js before the store variable is injected

Your third approach should work just fine for browser side rendering.

You can dispatch the action after creating the store in entry/browser.js
For example: 
`const store = createNewStore(client);`
`store.dispatch(setCurrentUser(user));`

**Comment by filtudo** [comment]
@akshitggrwl on browser it actually sets the right state, the problem appears on build-run where i get an warning saying that one of the props that were in localStorage is different on client then server:  Warning: Prop `aria-selected` did not match. Server: "true" Client: "false" and the rendered output looks a bit messed up(the server and client overlaps).

So i guess the problem is https://reactjs.org/docs/react-dom.html#hydrate at "React expects that the rendered content is identical between the server and the client."

**Comment by akshitggrwl** [comment]
Either your server state is correct or browser state. Either way you need to make sure that your initial states are same on both server and browser.

**Comment by leebenson** [comment]
Apologies for the generic response, but I've released a new [v3.0 kit](https://github.com/leebenson/reactql/releases/tag/3.0.0), which has been re-written from the ground up.

It bumps the ReactQL stack to Webpack 4, React 16.4, Apollo Client 2.0, and adds Styled Components, full SSR (even in development), and has been re-written in Typescript. It's leaner, faster and has been brought completely up-to-date.

If you're still using ReactQL (and I appreciate you may not be, given the time lag in my response), I'd recommend checking out the new kit to see if your issue has been answered. If not, please feel free to post a new issue at https://github.com/leebenson/reactql
