### ISSUE TITLE
Best approach for routing / static build 

### ISSUE THREAD

**Issue by mkotar** [reactql/kit#148]
Hi,
what is the best, suggested approach for having working routing on static builds?

when you open: http://localhost:5000, navigate to contact and hit refresh I would like to get contact page loaded. Instead of this I get 404 on prod server (where I only serve /public files) and some console errors when running on my local machine.

**Comment by leebenson** [comment]
Apologies for the generic response, but I've released a new [v3.0 kit](https://github.com/leebenson/reactql/releases/tag/3.0.0), which has been re-written from the ground up.

It bumps the ReactQL stack to Webpack 4, React 16.4, Apollo Client 2.0, and adds Styled Components, full SSR (even in development), and has been re-written in Typescript. It's leaner, faster and has been brought completely up-to-date.

If you're still using ReactQL (and I appreciate you may not be, given the time lag in my response), I'd recommend checking out the new kit to see if your issue has been answered. If not, please feel free to post a new issue at https://github.com/leebenson/reactql
