### ISSUE TITLE
Bootstrap 4 SASS error

### ISSUE THREAD

**Issue by carcus88** [reactql/kit#149]
Including the latest bootstrap 4.0.0 as a SASS module fails to compile because somewhere in the chain this line breaks.

    $navbar-light-toggler-icon-bg:      str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cpath stroke='#{$navbar-light-color}' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E"), "#", "%23") !default;

The error is 

    Error: Module build failed: Syntax Error 
    (4344:57452) Unclosed block

I've check  and its compiled correctly libsass so it seems that a processor after libsass runs is chocking on it. If you replace the single quotes with escaped double quotes it works fine.

    $navbar-light-toggler-icon-bg:      str-replace(url("data:image/svg+xml;charset=utf8,%3Csvg viewBox=\"0 0 30 30\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 8 8\"%3E%3Cpath stroke=\"#{$navbar-light-color}\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-miterlimit=\"10\" d=\"M4 7h22M4 15h22M4 23h22\"/%3E%3C/svg%3E"), "#", "%23") !default;

**Comment by aoighost** [comment]
I'm getting this issue as well. which file did you edit and where?

**Comment by carcus88** [comment]
@aoighost I edited _variables.scss where the "$navbar-light-toggler-icon-bg:" variable is defined around line 647

**Comment by leebenson** [comment]
Apologies for the generic response, but I've released a new [v3.0 kit](https://github.com/leebenson/reactql/releases/tag/3.0.0), which has been re-written from the ground up.

It bumps the ReactQL stack to Webpack 4, React 16.4, Apollo Client 2.0, and adds Styled Components, full SSR (even in development), and has been re-written in Typescript. It's leaner, faster and has been brought completely up-to-date.

If you're still using ReactQL (and I appreciate you may not be, given the time lag in my response), I'd recommend checking out the new kit to see if your issue has been answered. If not, please feel free to post a new issue at https://github.com/leebenson/reactql
