### ISSUE TITLE
Proper SEO / Helmet Implementation 

### ISSUE THREAD

**Issue by MassivDash** [reactql/kit#153]
Hello. 
I am having hard time passing all needed seo meta tags to the SSR.js component. 
So I have a seo component, with all meta info, however it does appear on the "ViewSource" during the initial load , the actual source code gets implemented on the refresh. 

On the dynamic pages it does not render the data at all, (obviously because it still fetches the data, while the page is being created). Does anybody have maybe a solid solution for this ?

**Comment by MassivDash** [comment]
Hello, thanks for quick reply, My seo component looks like this. When using the facebook debugger it shows proper data, after few refresh clicks (2, 3). The seo is  called inside the "Page component" with props (not dynamic for now, just strings), inside a <switch> <Route path="/Page" component="page"></switch>   


import React, { Component } from 'react';
import Helmet from 'react-helmet';

    class SEO extends Component {
        render() {

            const site = "Plenerowe Kino, Warszawa i okolice";
            const blogURL = "https://plenerowekino.pl";
            const postURL = `https://plenerowekino.pl/${this.props.postURL}`;
            const image = this.props.image;
            const title = this.props.title;
            const description = this.props.description;

            
            const schemaOrgJSONLD = [
            {
              "@context": "http://schema.org",
              "@type": "WebSite",
              url: "https//plenerowekino.pl",
              name: "Kino Plenerowe Warszawa i okolice",
              alternateName: "Kino Plenerowe Warszawa i okolice"
            }
          ];
          
            schemaOrgJSONLD.push([
              {
                "@context": "http://schema.org",
                "@type": "BreadcrumbList",
                itemListElement: [
                  {
                    "@type": "ListItem",
                    position: 1,
                    item: {
                      "@id": this.props.postURL,
                      name: site,
                      image
                    }
                  }
                ]
              },
              {
                "@context": "http://schema.org",
                "@type": "BlogPosting",
                url: blogURL,
                name: title,
                alternateName: site,
                headline: title,
                image: {
                  "@type": "ImageObject",
                  url: image
                },
                description
              }
            ]);
          
          return (
            <Helmet>
              {/* General tags */}
              <title>Plenerowe kino, Warszawa i okolice</title>
              <meta name="description" content={description} />
              <meta name="image" content={image} />
      
              {/* Schema.org tags */}
              <script type="application/ld+json">
                {JSON.stringify(schemaOrgJSONLD)}
              </script>
      
              {/* OpenGraph tags */}
              <meta property="og:url" content={postURL} />
              <meta property="og:type" content="article" /> 
              <meta property="og:title" content={title} />
              <meta property="og:description" content={description} />
              <meta property="og:image" content={image} />
              <meta
                property="fb:app_id"
                content="1852631914989608"
              />
      
              {/* Twitter Card tags */}
              <meta name="twitter:card" content="summary_large_image" />
              <meta
                name="twitter:creator"
                content="plenerowekino"
              />
              <meta name="twitter:title" content={title} />
              <meta name="twitter:description" content={description} />
              <meta name="twitter:image" content={image} />
            </Helmet>
          );
        }
      }
      
      export default SEO;


Thanks for any help, most probably everything is fine with ReactQL, I think i just implementing it wrong. 

My second question would be, if I have a another component that is generated via graphql query with variable ID passed into it, if there is a way to use that data to render SEO component ?

**Comment by leebenson** [comment]
Apologies for the generic response, but I've released a new [v3.0 kit](https://github.com/leebenson/reactql/releases/tag/3.0.0), which has been re-written from the ground up.

It bumps the ReactQL stack to Webpack 4, React 16.4, Apollo Client 2.0, and adds Styled Components, full SSR (even in development), and has been re-written in Typescript. It's leaner, faster and has been brought completely up-to-date.

If you're still using ReactQL (and I appreciate you may not be, given the time lag in my response), I'd recommend checking out the new kit to see if your issue has been answered. If not, please feel free to post a new issue at https://github.com/leebenson/reactql
