### ISSUE TITLE
Probably a noob question - Linking static files/images

### ISSUE THREAD

**Issue by doctorniz** [reactql/kit#154]
How do I link to files in my static folder - especially images, I've seen the import example for the favicon.svg, but I need to not import it - the url/relative path is/will be delivered from a database as a string to a react component as a prop.

`<Card image={props.imageURL} />`

How do I edit imageURL to display the correct path. Currently my images are saved in the static>uploads>img folder.

In express, we could use static Middleware - I have a feeling this has already been loaded, I've been looking through the code and haven't been able to work it out and experimented with various different route examples. 

Thanks in advance

**Comment by leebenson** [comment]
Apologies for the generic response, but I've released a new [v3.0 kit](https://github.com/leebenson/reactql/releases/tag/3.0.0), which has been re-written from the ground up.

It bumps the ReactQL stack to Webpack 4, React 16.4, Apollo Client 2.0, and adds Styled Components, full SSR (even in development), and has been re-written in Typescript. It's leaner, faster and has been brought completely up-to-date.

If you're still using ReactQL (and I appreciate you may not be, given the time lag in my response), I'd recommend checking out the new kit to see if your issue has been answered. If not, please feel free to post a new issue at https://github.com/leebenson/reactql
