### ISSUE TITLE
Package Vulnerabilities

### ISSUE THREAD

**Issue by hpartidas** [reactql/kit#156]
Hi,

I'm currently thinking about using this package but it is plagued with vulnerabilities.

Is there a plan to update the dependencies to weed out the vulnerabilities?

**Comment by leebenson** [comment]
From the readme:

> Not (currently) maintained
>
I'm taking some time off OSS, and focusing on commercial projects. It's unlikely I'll be making any changes to ReactQL anytime soon, so please know that before basing your next project off of any code you find here.
>
> That's not to say that I'll never update it, just that it's not currently on my radar. Feel free to fork and extend. Enjoy!

Open to PRs, but updating all of the packages to the latest versions to resolve vulnerabilities would be a massive can of worms, requiring a _lot_ of changes elsewhere in the code base.

**Comment by leebenson** [comment]
Ignore what I said. [I did the work.](https://github.com/leebenson/reactql)
