### ISSUE TITLE
Adding plugins preset in babelrc file

### ISSUE THREAD

**Issue by mairh** [reactql/kit#16]
Hi, I am trying to incorporate ant-design UI framework with reactql. In order to make the component imports modularized, I need to set [babel-plugin-import](https://github.com/ant-design/babel-plugin-import) in `.babelrc` file as suggested over here [Use-modularized-antd](https://ant.design/docs/react/introduce#Use-modularized-antd)

```
// .babelrc or babel-loader option
{
  "plugins": [
    ["import", { libraryName: "antd", style: "css" }] // `style: true` for less
  ]
}
```
However, the styles from the UI framework are not passed down to the react component. It works if I manually import the styles [manual style import](https://ant.design/docs/react/introduce#Usage).

Do I need to add the `babel-plugin-import` in the webpack file to make the styles import work?

**Comment by leebenson** [comment]
Yes, your config needs to go in `kit/webpack` and **_not_** the root `.babelrc` -- that file exists only to start the initial build. Settings there don't get fed through to your components.

**Comment by mairh** [comment]
Due to some reason, I can't get ant-deign to work with reactql. However, I guess it is our of scope for this kit at this moment

**Comment by leebenson** [comment]
@mairh - post your webpack config here, and I'll take a look

**Comment by mairh** [comment]
So this is what I did:

`yarn add antd`
`yarn add babel-plugin-import`

In `webpack/server.js`
```
// .js(x) files can extend the `.babelrc` file at the root of the project
      // (which was used to spawn Webpack in the first place), because that's
      // exactly the same polyfill config we'll want to use for this bundle
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          presets: [
            'react',
          ],
          plugins: [
            'transform-object-rest-spread',
            'syntax-dynamic-import',
            'transform-class-properties',
            'transform-decorators-legacy',
            'import', { 'libraryName': 'antd', 'style': true } // added the loader here
          ],
        },
      },
```
and in app.js I am trying out [Example](https://ant.design/components/button/#When-To-Use)

`import { Button } from 'antd';`
`<Button type="primary">Primary</Button>`

I am not sure in which webpack file the loader configuration should go? In webpack/server.js styles are not loaded from `antd`

**Comment by mairh** [comment]
The only way I can make it work if I forget about `babel-plugin-import` and import stuff manually from `antd` for e.g

in `kit/src/app.js`
`import { Button } from 'antd';`

and in `kit/src/style.global.css`
`@import 'node_modules/antd/dist/antd.css';`

as explained [here](https://ant.design/docs/react/use-with-create-react-app#Import-antd)

**Comment by jtmthf** [comment]
@mairh It looks like your only including `babel-plugin-import` in `webpack/server.js` which specifys the build configuration for the server that handles SSR. In addition to that, you also need to include additional Babel plugins in `webpack/browser.js` which is your client side configuration. For your case, it should look something like the config below. Hope that helps!

```js
{
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: [
          {
            loader: 'babel-loader',
            query: {
              // Ignore the .babelrc at the root of our project-- that's only
              // used to compile our webpack settings, NOT for bundling
              babelrc: false,
              presets: [
                ['env', {
                  // Enable tree-shaking by disabling commonJS transformation
                  modules: false,
                  // Exclude default regenerator-- we want to enable async/await
                  // so we'll do that with a dedicated plugin
                  exclude: ['transform-regenerator'],
                }],
                // Transpile JSX code
                'react',
              ],
              plugins: [
                'transform-object-rest-spread',
                'syntax-dynamic-import',
                'transform-regenerator',
                'transform-class-properties',
                'transform-decorators-legacy',
                'import', { 'libraryName': 'antd', 'style': true },
              ],
            },
          },
        ],
      },
```

**Comment by mairh** [comment]
@jtmthf @leebenson Sorry, I didn't mention earlier but I did try to add `babel-plugin-import` earlier in `webpack/browser.js`, but it is throwing an error 

`Error: Plugin 6 specified in "base" provided an invalid property of "libraryName"`

<img width="1082" alt="screen shot 2017-04-25 at 11 11 51" src="https://cloud.githubusercontent.com/assets/4072250/25375129/6878a276-29a8-11e7-8100-2570184c0ccd.png">

**Comment by jtmthf** [comment]
@mairh I see it now. You need square brackets around plugins that take options. It should look like,
`['import', { libraryName: 'antd', style: true }],`

**Comment by mairh** [comment]
@jtmthf Thanks. It does get rid of the webpack error after using the correct syntax. However, the styles for the corresponding component is not loaded.

In the below example I am just trying to import `tabs`

```
import { Tabs } from 'antd';
const TabPane = Tabs.TabPane;

function callback(key) {
  console.log(key);
}

ReactDOM.render(
  <Tabs defaultActiveKey="1" onChange={callback}>
    <TabPane tab="Tab 1" key="1">Content of Tab Pane 1</TabPane>
    <TabPane tab="Tab 2" key="2">Content of Tab Pane 2</TabPane>
    <TabPane tab="Tab 3" key="3">Content of Tab Pane 3</TabPane>
  </Tabs>
, mountNode);
```

as specified here [Tabs](https://ant.design/components/tabs/) 

and the styles are not injected

<img width="1440" alt="screen shot 2017-04-25 at 11 48 39" src="https://cloud.githubusercontent.com/assets/4072250/25376671/adbe2db0-29ad-11e7-82a0-7b37cf399411.png">


Could it be how we handle the style loader and splitting in reactql. The only styles are loaded in the the app is the root index styles from `antd`, which is `/node_modules/antd/lib/style/index.css` and it overrides the whole application styles on root level

<img width="1440" alt="screen shot 2017-04-25 at 11 50 20" src="https://cloud.githubusercontent.com/assets/4072250/25376821/2ae6b51e-29ae-11e7-9a58-1be2f03160f0.png">


Is there any workaround to solve this issue. For reference https://ant.design/docs/react/use-with-create-react-app#Import-on-demand

**Comment by jtmthf** [comment]
So the problem here is that the antd styles are being processed through css modules which is causing all of the class names to get clobbered. This can be a little tricky depending on what you want to do. If you know that you will not be using css-modules at all, you can disable them entirely. Alternatively you could also find a way in the config to disable css modules in files from `node_modules`.

**Comment by leebenson** [comment]
Have you tried creating an antd.global.css file and importing antd/lib/style/index.css from there?

**Comment by mairh** [comment]
yeah, as I mentioned in my earlier comment https://github.com/reactql/kit/issues/16#issuecomment-296776953 the only way to make the UI library work if I import the whole `antd` global styles and forget about babel-plugin-import way of doing it. However, the bundle size is massive if I simply import whole style file. 

<img width="789" alt="screen shot 2017-04-25 at 12 51 26" src="https://cloud.githubusercontent.com/assets/4072250/25379515/f1845760-29b5-11e7-84e7-f1e581c606c5.png">

I understand that `reactql` is not build to support all UI frameworks out there and that is not the main vision of `reactql`. I can simply drop the idea of using `antd` if it requires significant amount of workaround or major changes in `reactql` webpack build system.

**Comment by Sburke0708** [comment]
Try ```["import", { "libraryName": "antd", "style": "css" }]``` instead
