### ISSUE TITLE
VSCode integration

### ISSUE THREAD

**Issue by jtmthf** [reactql/kit#20]
Would it be worth having a `.vscode` settings directory integrated with the project? I hate to make an assumption that another developer is going to use VSCode, but a lot of functionality could be provided by providing this integration. Some benefits that I can think of include

- smart defaults related to styling and configuration in the settings
  - rulers
  - eslint auto fix on save
  - remove trailing white space while typing
  - hide unimportant directories and files from tree view
- build and start tasks defined
- out of the box support for in editor debugging.

**Comment by leebenson** [comment]
Sure, makes sense. We already have ESLint and per #19 now `.editorconfig`, so a `.vscode` folder isn't a big deal. With the Typescript version now in the CLI, I imagine quite a few devs will be using VSCode anyway.

**Comment by leebenson** [comment]
@jtmthf - did you want to tackle this one?

With #24 throwing errors in the latest eslinting plugins and VSCode looking unaffected, I'd like to make VS support 'official' as an alternative.

**Comment by leebenson** [comment]
I'll close this for now - feel free to submit a PR though @jtmthf if it's something you want in.
