### ISSUE TITLE
Provide Relay Modern integration in docs.

### ISSUE THREAD

**Issue by Extra-lightwill** [reactql/kit#23]
**Suggestion:** With the release of Relay Modern yesterday, it would be cool to have a Relay integration included within the documentation for ReactQL.

I'm not saying a Relay version of ReactQL needs to be spun up at this point in time but instead providing guidelines in the docs for how-to/best practices on Relay integration would satisfy most use-cases.

Realise this adds extra complexity but it could also benefit the adoption of ReactQL by opening it up to a wider audience - and by keeping Relay-related info in the documentation rather than adding it to the codebase there will be less confusion.

Thoughts?

**Comment by leebenson** [comment]
Sure, makes sense. Tracked in https://github.com/reactql/docs/issues/7

**Comment by Extra-lightwill** [comment]
***Tracked in https://github.com/reactql/old_docs/issues/7
