### ISSUE TITLE
i18n internationalisation

### ISSUE THREAD

**Issue by leebenson** [reactql/kit#26]
Figure out the best way to approach internationalisation.

**Comment by leebenson** [comment]
I'm working on an i18n implementation today. Requirements:

- Easy for non-techs to write a 'translation' file, that's imported and used by components.
- Full i18n: Proper handling of pluralisation, number formatting, dates currencies.
- Relatively lightweight.
- Only shows the data that's relevant to the current view.
- Avoids 'language flicker', where possible
- Components can specify message keys, and just those keys are loaded - i.e. avoid loading the full translation file on every page load, for components that may not be rendered on the screen.

To satisfy the above, the best approach I can currently think of is to run a separate GraphQL server inside the Koa server, that reads from a JSON/YAML translation file and responds with the messages that pertain to the correct locale.

On the client side, this could mean inheriting Apollo's native caching, `getDataFromTree()` awaiting of data being ready, and its injection into the Redux store.

I need to figure out:

* Which translation lib to use (so far, thinking https://github.com/yahoo/react-intl for its completeness)
* How to properly detect locale on the server, and pass that down via store state so the client can re-use it. (https://github.com/tinganho/node-accept-language ?)
* How to avoid issues with `npm run build-static`, whilst also needing a GraphQL server for translations. IMO, keeping this in GraphQL is keeping with the raison d'être of the kit, but it does add an additional layer of complexity out the box for having to maintain a separate server.

**Comment by zachlendon** [comment]
Will this be an optional addition for ReactQL users? I ask, since not everyone will want/need i18n support and some will have their own implementations, for whatever reason.  I get that folks could "rip it out", but just wondering what the impact might be...

**Comment by leebenson** [comment]
It'll probably be included in core, since otherwise it's a separate branch/repo that needs maintaining, and I'd rather not go down the route of splintering the core kit if it can be helped.

However, I want to make it simple to disable -- it'll likely just mean commenting out the server route adds the GraphQL server.

This is a tricky pattern to get right... I haven't seen many (any?) starter kits that do i18n _properly_ without over-loading data, or causing some kind of language flicker. The fact that we're already doing stuff with GraphQL gives us a unique and relatively lightweight means to bolt-on internationalisation.

I think it's a good opportunity to offer it to ReactQL users out-the-box. It's one of those core considerations that the majority of users probably don't need... but once you hit any kind of volume, suddenly becomes a giant PITA to add. Hopefully, we'll wind up with a pattern here that solves it from the start, but is easy to disable if it never needs to be a concern.

**Comment by leebenson** [comment]
After playing with this a little, I'm thinking this is perhaps something that might make a good candidate for an 'examples' repo of runnable starter kits, rather than something that has first-class support in the core.

I hacked together a quick working demo with a local GraphQL server and an object of messages that could be filtered by key. Beyond that, the issues stack up quickly. `react-apollo` doesn't currently accept more than one client (there's a thread at https://github.com/apollographql/react-apollo/issues/464 tracking the feature), so implementing a local translation endpoint via GraphQL means foregoing a simple Graph.cool example and assuming it'll always be available-- something that immediately breaks static building.

I can probably live with an opinionated framework for i18n, as long as that means it also brings with it a complete set of date/string/number features, but more difficult is figuring out a 'translation file' loading strategy that works for every use case. Pulling translation content from, say, a local JSON object, means the user that wants to store that stuff in a DB needs to re-factor / yank out a whole bunch of boilerplate that isn't relevant. i18n is something that tends to be needed right at the root/core of a project, so swapping it out for, say, i18next as a preference isn't quite so trivial.

I can see this would quickly get hairy, and as you hinted @zachlendon, this is probably at the cost of users that don't want/need it.

Will re-visit when it comes to putting together some example projects. I might also do a tutorial series in the docs; this would be a decent candidate.

**Comment by jtmthf** [comment]
@leebenson I agree that's the approach to take. Most times I've worked with internationalization in the past, it's been integrated into the app's API layer which is what I prefer for most situations. For an example with SSR, Koa's built in `request.acceptsLanguages(langs)` would be a good candidate for picking up the language header.

I would warn though that the `accepts-language` isn't all that effective for picking a language though. Globally be default, most users have it set to `en-us` because they don't know how to change it. It seems that most production sites either do ip filtering or have distinct sub-domains or paths. This is a good reason for not baking it into ReactQL as there doesn't seem to be a "best" solution. Perhaps the documentation could have multiple examples of how to handle language selection.

**Comment by leebenson** [comment]
good thoughts @jtmthf - definitely one for an 'examples' repo.
