### ISSUE TITLE
'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by kajohnsonjd** [reactql/kit#27]
Hi there.  I love this boilerplate but have bumped up against this import/export error in multiple places in my code.  

React hot loader indicates that this error may occur with RHL v3 in Webpack if React Hot Loader isn't loaded to the left of Babel in loaders array in Webpack config. [here, midpage](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md)  Having tried several changes in kit-level config without success I've now reverted to core kit config.  Suggestions?

**Comment by kajohnsonjd** [comment]
Found the problem...dynamic projects should be using `require` or `require.ensure` rather than `import `and `export` due to Webpack code-splitting.

**Comment by leebenson** [comment]
You should actually be able to use `import` anywhere when it's used [as a Promise, like in this code-splitting example](https://github.com/reactql/kit/issues/5#issuecomment-295200869).

`export` should always be top-level.

**Comment by kajohnsonjd** [comment]
Thanks.  Extremely helpful example.

**Comment by kgregory** [comment]
This is a note to anyone who ends up here in the future:

If you're running into this issue while implementing code-splitting, you may need to install [babel-plugin-syntax-dynamic-import](https://babeljs.io/docs/plugins/syntax-dynamic-import/) take a look at [this response](https://babeljs.io/docs/plugins/syntax-dynamic-import/) from @feross:
>It looks like import() is still in stage 3 of the standardization process. ESLint has a policy of only implementing features in their parser once they're in stage 4.
>
>So, standard will support this eventually, but not until the spec is stable.
>
>You can try installing this babel plugin (https://babeljs.io/docs/plugins/syntax-dynamic-import/) and tell standard to use Babel as it's parser if you want to be on the bleeding edge.

**Comment by andreshg112** [comment]
@kgregory, I already did it and I still have the same issue:
![image](https://user-images.githubusercontent.com/15859884/43488513-ab93cf9c-94df-11e8-9ceb-200c09d0d37f.png)

Log file
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test:unit' ]
2 info using npm@6.1.0
3 info using node@v9.11.2
4 verbose run-script [ 'pretest:unit', 'test:unit', 'posttest:unit' ]
5 info lifecycle issues-frontend@0.1.0~pretest:unit: issues-frontend@0.1.0
6 info lifecycle issues-frontend@0.1.0~test:unit: issues-frontend@0.1.0
7 verbose lifecycle issues-frontend@0.1.0~test:unit: unsafe-perm in lifecycle true
8 verbose lifecycle issues-frontend@0.1.0~test:unit: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/andreshg112/Projects/Vue/issues-frontend/node_modules/.bin:/home/andreshg112/Programs:/home/andreshg112/.config/composer/vendor/bin:/opt/lampp/bin:/home/andreshg112/bin:/home/andreshg112/.local/bin:/home/andreshg112/Programs:/home/andreshg112/.config/composer/vendor/bin:/opt/lampp/bin:/home/andreshg112/bin:/home/andreshg112/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle issues-frontend@0.1.0~test:unit: CWD: /home/andreshg112/Projects/Vue/issues-frontend
10 silly lifecycle issues-frontend@0.1.0~test:unit: Args: [ '-c', 'vue-cli-service test:unit' ]
11 silly lifecycle issues-frontend@0.1.0~test:unit: Returned: code: 1  signal: null
12 info lifecycle issues-frontend@0.1.0~test:unit: Failed to exec test:unit script
13 verbose stack Error: issues-frontend@0.1.0 test:unit: `vue-cli-service test:unit`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid issues-frontend@0.1.0
15 verbose cwd /home/andreshg112/Projects/Vue/issues-frontend
16 verbose Linux 4.15.0-29-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test:unit"
18 verbose node v9.11.2
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error issues-frontend@0.1.0 test:unit: `vue-cli-service test:unit`
22 error Exit status 1
23 error Failed at the issues-frontend@0.1.0 test:unit script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
