### ISSUE TITLE
Styles not loading

### ISSUE THREAD

**Issue by auser** [reactql/kit#28]
I've tried to peek around the webpack config, but there's a bit of magic in here. Basically, the `styles.css` (`less/sass/css`) don't compile when named anything other than `style`.css. 

For example, I have a `Landing.css` file sitting next to a `Landing.js` file and loading the `./Landing.css` from the JS module explodes with the error:

```javascript
Failed to compile.

(undefined) ./src/views/Public/Landing/landing.css
Module parse failed: ...src/views/Public/Landing/landing.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .landing {
|   color: blue;
| }
 @ ./src/views/Public/Landing/Landing.js 7:0-35
 @ ./src/app.js
 @ ./kit/entry/browser.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./kit/entry/browser.js
``` 

However, when I rename the file to `style(s).css`, the file loads. Any idea why/where this is happening?

**Comment by leebenson** [comment]
@auser - can you please provide a dump of the the parent code that attempts to import the style file?

It should definitely be fine to import .css / .scss / .less files prefixed with any name -- the loaders only look at the extension; it shouldn't care what comes before it.

Renaming `src/styles.css` to `src/whatever/SomethingElse.css`, for example, works fine in a fresh new project:

**src/app.js**
```js
// ...

// Styles
import './styles.global.css';
import css from './whatever/SomethingElse.css';
import sass from './styles.scss';
import less from './styles.less';

// ...
```

In the browser...

<img width="736" alt="screen shot 2017-05-23 at 05 27 06" src="https://cloud.githubusercontent.com/assets/719722/26338546/bf8041e2-3f78-11e7-830d-78e222524392.png">

Did you change the webconfig at all?

Are you invoking webpack via the standard method -- e.g. `npm start` and/or `npm run build`?

**Comment by auser** [comment]
I am using the same webpack version. I can give you a git dump as well Mind writing me an email so I can send you the project (literally a fresh project) with a small update to the webpack config (added to the `modules.root`).

**Comment by leebenson** [comment]
@auser - please post your code as a public repo that I can download, or as a [gist](https://gist.github.com/) of the changes you made, and I'll take a look.

**Comment by leebenson** [comment]
@auser - I'll close this for now, since it seems like something to do with your environment. Feel free to re-open if you have code for me to look at.
