### ISSUE TITLE
node-sass errors

### ISSUE THREAD

**Issue by loelsonk** [reactql/kit#37]
I found small bugs. 

It is related to what I have said on reactql/docs#1.

---

Anytime I add new package I have to `npm rebuild node-sass` to get my project back to work.

Here is console output I am getting:

![image](https://i.imgur.com/KQwNhcP.png)

---

Another `node-sass` related error. I am getting is when I try to add new package eg. `semantic-ui`. I just can't do it when my webpack dev server is up and running. I have to stop the script first.

Console output:

```
E:\projekty_node\netins>yarn add semantic-ui
yarn add v0.24.5
[1/4] Resolving packages...
warning semantic-ui > gulp-clean-css@2.4.0: breaking changes from clean-css 4.x. Please install gulp-clean-css 3.x
warning semantic-ui > gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning semantic-ui > gulp-clone > through2 > xtend > object-keys@0.4.0:
warning semantic-ui > gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning semantic-ui > gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the
tree.
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'E:\\projekty_node\\netins\\node_modules\\node-sass\\vendor\\win32-x64-51\\binding.node'".
info If you think this is a bug, please open a bug report with the information provided in "E:\\projekty_node\\netins\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by leebenson** [comment]
That sounds like some kind of error with either node-sass or NPM. I'm not sure how ReactQL can have much control over the packaging process.

Generally, I do `rm -rf node_modules; npm i` whenever there's a major change. I've not faced the edge-case of having to rebuild node-sass with every package addition, though. I can usually just `npm i -S <package>` and be done with it. Maybe an NPM thing?

Re: adding packages on-the-fly, this is probably going to be hard to do. When webpack-dev-server runs, it's listening to file system changes. If you're half-way through installing a package, that could break whatever's currently loaded/locked. I'm not sure if there's any way around this. I personally would always recommend installing a new package 'cleanly' by ensuring there are no locks on `node_modules`. It's a bit of a pain if you're installing a bunch of stuff and trying it out live, but for the 10 seconds or so it takes to restart the dev server, isn't _that_ big of a deal in the grand scheme.

If there are any techniques for handling 'hot' `node_modules` changes, I'd definitely be open to a PR or even to implementing it myself.
