### ISSUE TITLE
Running SSR server in development

### ISSUE THREAD

**Issue by leebenson** [reactql/kit#4]
Per https://github.com/reactql/cli/issues/13

**Comment by leebenson** [comment]
@jtmthf - including you on this, to track progress

**Comment by leebenson** [comment]
@jtmthf - do you still want to tackle this one? I'm making some improvements over the weekend, and I'm happy to tackle this one if it's not currently on your radar.

**Comment by jtmthf** [comment]
@leebenson I'm going to be pretty busy over the weekend so I won't be able to myself. I've played around with this, but haven't had the time to fully commit. My plan was to use [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) as it supplies middleware for both the dev server and hmr. What I haven'y fully figured out is the best way to split the existing server into a production and dev mode without duplicating too much.

**Comment by leebenson** [comment]
@jtmthf - ok, np, I'll try and tackle this weekend. On my radar is i18n support and a code splitting helper. If I have time left over, I'll get to the server dev.

**Comment by leebenson** [comment]
FYI, I should have a working implementation of SSR in development today.

**Comment by leebenson** [comment]
**Update: this will be the new `npm start`**, being pushed with the v1.3 release tomorrow:

<img width="633" alt="screen shot 2017-05-25 at 00 51 55" src="https://cloud.githubusercontent.com/assets/719722/26430339/626a9e40-40e4-11e7-9d0e-fb06aefcaf9f.png">

When you run `npm start`, this will happen:

1. A hot-reloading browser will spawn on port 8080, the same as ever.
2. Additionally, a full web server will spawn on 8081.
3. Whenever you make a change to any non-Webpack file, changes will be hot-pushed to port 8080, and the server on 8081 will rebuild and restart (usually in less than a second, start to finish)
4. Both will build 'development' bundles-- with full source maps, debug messages, etc.

This should make development significantly faster for testing against a live web server.

**Comment by babsonmatt** [comment]
@leebenson very cool

**Comment by zachlendon** [comment]
@leebenson how's 1.3 looking?

**Comment by leebenson** [comment]
@zachlendon - apologies for the delay... I'm a couple of days behind... crazy workload in my day job... aiming to get 1.3 up by the weekend. Bear with me 😅

**Comment by zachlendon** [comment]
No problem,  totally understandable.  Huge fan of the project, and hoping to help in time.  Was just curious.
