### ISSUE TITLE
[Webpack config] stage 3 for koa-send

### ISSUE THREAD

**Issue by ClemensSahs** [reactql/kit#42]
Is this a know issues?

./node_modules/koa-send/index.js:37
async function send (ctx, path, opts = {}) {
      ^^^^^^^^
SyntaxError: Unexpected token function

I got this in every blank installation. Browser Build work fine.

**Comment by leebenson** [comment]
Upgrade to the latest version of Node, where `async/await` is available.

**Comment by ClemensSahs** [comment]
@leebenson oh... realy... sorry my mistake
