### ISSUE TITLE
Windows problem on browser-dev after updating

### ISSUE THREAD

**Issue by kajohnsonjd** [reactql/kit#43]
I have run through the code and could not locate the problem.  No changes to the config other than the Apollo url for my backend.  Could be that I did the update incorrectly.

![image](https://user-images.githubusercontent.com/18404204/27733854-539c31a0-5d66-11e7-94bd-2943475db97e.png)

![devserveroutput](https://user-images.githubusercontent.com/18404204/27733707-82a5e0dc-5d65-11e7-90af-f66124325792.JPG)

**Comment by leebenson** [comment]
When you say 'updating', what do you mean exactly? Did you start a new project with the [CLI](https://github.com/reactql/cli) and copy your custom app code over, or did you update the kit from _within_ your current project?

**Comment by kajohnsonjd** [comment]
Inside the file I moved my src code and config, deleted everything else, upgraded ReactQL and ran the CLI and then added my src back in.  Glad I kep the config because it oddly didn't appear and had to add it in, but Ive double checked it against kit and it appears to be the same.

**Comment by leebenson** [comment]
If you had to add in the `kit/webpack` config manually, then something definitely went wrong with your update.

The official recommendation is to run `reactql new` in a new folder, move over your custom `src`, and re-add your `kit` and NPM packages.

Try that, and if it still doesn't work, feel free to re-open.
