### ISSUE TITLE
Peer dep missing after update 1.11.0 - 2017-06-30

### ISSUE THREAD

**Issue by balciseri** [reactql/kit#44]
After updating reactql, eslint stopped working.
With this error: https://github.com/airbnb/javascript/issues/1454
This is why : https://github.com/airbnb/javascript/issues/1447
airbnb doesn't support eslint v4

To reproduce:
```
npm i -g reactql
reactql n
```
Just press enter to get the defaults.
`cd reactql-app`
and run
`npm ls`
this is what you'll get:
```
npm ERR! peer dep missing: eslint@^3.19.0, required by eslint-config-airbnb@15.0.1
npm ERR! peer dep missing: eslint-plugin-jsx-a11y@^5.0.1, required by eslint-config-airbnb@15.0.1
npm ERR! peer dep missing: webpack@^2.0.0 || ^2.1.0-beta || ^2.2.0-rc, required by chunk-manifest-webpack-plugin@1.1.0
npm ERR! peer dep missing: webpack@^2.2.0, required by extract-text-webpack-plugin@2.1.2
npm ERR! peer dep missing: webpack@^2.2.0, required by less-loader@4.0.4
npm ERR! peer dep missing: webpack@^1.3.0 || ^2 || ^2.1.0-beta || ^2.2.0-rc, required by progress-bar-webpack-plugin@1.9.3
npm ERR! peer dep missing: webpack@^2.2.0, required by webpack-dev-server@2.5.0
npm ERR! peer dep missing: eslint@^3.19.0, required by eslint-config-airbnb-base@11.2.0
```

**Comment by leebenson** [comment]
@balciseri - good catch- I knew there was a reason I'd held off from bumping to Webpack v3 before now, but it seemed to be working locally. I'll revert to v2 in the next version.

I've got 'add tests' on my to-do to avoid this kinda thing in future.

**Comment by leebenson** [comment]
In [1.12.0](https://github.com/reactql/kit/releases/tag/1.12.0), I reverted to ESLint v3 which fixed `npm run lint`.

There are still a few peer-dependency issues due to the Webpack v3 bump, but they're just warnings; Webpack still works well, and produces smaller bundle sizes too.

I also added a Travis CI step to verify that the kit can build and passes linting.
