### ISSUE TITLE
Where to put non-changing web assets?

### ISSUE THREAD

**Issue by claym** [reactql/kit#51]
Less a issue than a question:

I've got a custom font I can't really link to elsewhere - what is the recommended location to put fonts or images that won't change frequently enough to worry about caching?

**Comment by leebenson** [comment]
Put them in `/static`.

Anything in that folder will get copied over to `dist/public` and made available publicly by your web server, but will avoid the transpilation pipeline. So images, fonts, PDFs etc will remain per their originals.
