### ISSUE TITLE
Heroku Deployment?

### ISSUE THREAD

**Issue by claym** [reactql/kit#52]
Has anyone deployed a ReactQL app to Heroku? 

It's not working especially smoothly right off the bat, and while I'm working through the issues, just wondering if anyone else has done it and happens to know the steps needed.

It's mostly complaining that stuff like run-p and cross-env aren't installed (they are in devDependencies)

Or perhaps I'm doing this all wrong :)

**Comment by leebenson** [comment]
@claym - check out https://github.com/reactql/cli/issues/45 and see if that helps. The issue is focused around port config, but it seems @lawwantsin was able to get a ReactQL app spinning with Heroku, so he may be able to offer some pointers for other parts if you're running into issues.

I'll eventually add an Heroku guide to the docs. It's not an environment I typically use, so I haven't given it any focus at this point, but I will.

**Comment by leebenson** [comment]
And feel free to re-open https://github.com/reactql/cli/issues/45 directly if you have any related issues.

**Comment by claym** [comment]
Ok, there was alllll sorts of issues with this thing

1) pretty much any package required by the build process needed to be moved to the dependencies.

2) the ports thing is an issue. Heroku tells the app which port to bind to via env.process.PORT, as opposed to whichever variable ReactQL binds to. Which wasn't really the most difficult thing to update, but it does require messing about with the internals of the kit, which isn't ideal.

3) the other issue is the host which the server binds to.

it's currently set to "localhost" - which works for local development, it doesn't bind the server to the LAN address (even though the startup banner says it's available at 192.168.x.x). To bind to localhost AND external, it would need to be 0.0.0.0.

However, this doesn't work, at least on Windows, as 0.0.0.0 isn't a valid IP address, and even if you attach to the LAN IP, hot reloader goes back to 0.0.0.0 which just means failures loading images and whatever other resources.

You can look at the commits here I did on 7/17/2017 to see all the things I had to do @ https://github.com/claym/sportsdespair/commits/master

**Comment by leebenson** [comment]
**Dynamic hosts**

Just like `SERVER_PROD_PORT=$PORT npm run server` in https://github.com/reactql/cli/issues/45, you can set `SERVER_PROD_HOST` for binding to a dynamic host.

https://stackoverflow.com/questions/22954782/install-devdependencies-on-heroku seems to solve the `devDependencies` thing on Heroku:

**Heroku and `devDependencies`**

> Heroku by default installs only the production dependencies, ignoring the development dependencies under devDependencies.
>
> Setting the npm production variable to false do the trick:
>
> `heroku config:set NPM_CONFIG_PRODUCTION=false`
>
> More info are available at the [Heroku Node.js Support page](https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process).

**Docker?**

The kit contains a [Dockerfile](https://github.com/reactql/kit/blob/master/Dockerfile) that takes care of building/bundling in a Linux environment, and will work anywhere.

Maybe that's a better solution for Heroku?

**Comment by claym** [comment]
Yeah, for the host, I used SERVER_PROD_HOST=0.0.0.0

As for the devDependencies thing, I took a few cues from relay-fullstack which seems to be aimed at Heroku.

I'll give Docker a try tonight.

**Comment by impavidum** [comment]
@claym were you able to get this working with Docker? I am currently attempting to deploy my docker image to heroku without success. Any help would be appreciated.

**Comment by jppgks** [comment]
I [successfully deployed to Heroku using Docker](https://github.com/leebenson/reactql/issues/45#issuecomment-457855223) with no extra config.
