### ISSUE TITLE
How to import CSS

### ISSUE THREAD

**Issue by bakystefan** [reactql/kit#53]
Hi, I'm using Reactql while making my personal website and I'm adressing you with an issue I'm having. I have a problem when a component I'm using for my gallery is expected to read my .css file. It is implied that a component is expecting me to @import url('link');  in styles.css. Also, I tried to import a link into my browser HTML file (knowing that is something I should not be doing) . Is there a possibility that I can get this working? Also, I have an issue with any google font's I try to import. Heroku is my deploy destination.

**Comment by leebenson** [comment]
Have you read https://reactql.org/docs/stylesheets/ ?

If you're still having issues after reading the docs, please re-open this and post some code, and I'll take a look.

**Comment by bakystefan** [comment]
Thanks man, i have resolved my problem in global css file.
