### ISSUE TITLE
Static building fails per `chunk-manifest-webpack-plugin`

### ISSUE THREAD

**Issue by leebenson** [reactql/kit#55]
Track https://github.com/soundcloud/chunk-manifest-webpack-plugin/issues/47#issuecomment-320508231

**Comment by edolyne** [comment]
@leebenson I'm running into this issue when building a static site. Is there a fix to allow static sites to be built?

**Comment by giovannimoreno** [comment]
@edolyne this is working for me 

`yarn add --dev https://github.com/sigerello/chunk-manifest-webpack-plugin.git#1.1.2-fix`

or (npm) `npm i --save-dev https://github.com/sigerello/chunk-manifest-webpack-plugin.git#1.1.2-fix`
