### ISSUE TITLE
add graphcool (or any) authentication

### ISSUE THREAD

**Issue by tsdexter** [reactql/kit#58]
Is there any plan to add an example with graphcool authentication (or any authentication) to show/hide routes/data for logged in users?

I think it'd be quite handy to see the 'done properly' way of doing this.

**Comment by leebenson** [comment]
I'm working on authentication this week. It'll handle OAuth and updating a local Redux store too. Will keep you posted.

**Comment by Bitti09** [comment]
👍

**Comment by leebenson** [comment]
FYI for related threads - see https://github.com/reactql/kit/issues/59#issuecomment-323509731 for an update on adding auth.

**Comment by leebenson** [comment]
See https://github.com/reactql/kit/issues/38#issuecomment-325102058 for an update

**Comment by leebenson** [comment]
Video explainer on YT -> https://youtu.be/s1p4R4rzWUs

I'll go ahead and close this now, but will update the thread once I've also added social logins.

**Comment by leebenson** [comment]
Passport.js has been integrated, with a Facebook example ->

https://github.com/reactql/examples/tree/master/auth

Video commentary to follow later.

**Comment by dougajmcdonald** [comment]
https://github.com/reactql/example-auth ;-)
