### ISSUE TITLE
Prevent modules: true for external libs with css

### ISSUE THREAD

**Issue by zunder** [reactql/kit#62]
I am using `antd` as a third party library for react components. Using reactql causes issues with styling, as it is not applied on the antd components leaving them naked. My best guess would be, that antd's css imports are treated as local module imports. If I set `modules: false` for all css loaders in `common.js` of webpack configuration, antd components are styled perfectly fine. I am not super familiar with webpack configuration, but is there an easy solution for still scoping my local css/less to be imported as modules, but leave everything else (basically `node_modules`) out of the css-loader?

**Comment by leebenson** [comment]
You shouldn't need to mess with webpack. Just add your CSS import statements to a `styles.global.css` file, and import that instead.

Anything that happens within `.global.(scss|sass|less|css)` file is preserved when exporting, so the original class names will remain.

Let me know if you run into any issues.

**Comment by zunder** [comment]
@leebenson 

You mean importing the third-party css through import in `styles.global.css`? Antd suggests the import of their styles through `babel-plugin-import` plugin, like this:

```
loaders: [
            {
                loader: 'awesome-typescript-loader',
                options: {
                    ...
                    babelOptions: {
                        babelrc: false,
                        presets: [
                            ...
                        ],
                        plugins: [
                            ...
                            ["import", { "libraryName": "antd", style: true }]
                        ],
                    },
                    ...
                }
            },
        ],     
``` 
While using this method, I had to do this change `common.js` for it to work:
```
getModuleRegExp(ext) {
    return [
        [`^(?:(?!node_modules\\/|\\.global).)*\\.${ext}$`, { modules: true }],
        [`((node_modules\\/).*)\\.${ext}$`, { modules: false } ],
        [`\\.global\\.${ext}$`, { modules: false }],
    ];
},
```

But I see that it is also possible to load the styles through the `styles.global.less` like you suggested and I guess this being a cleaner way. Thank you for the hint!

**Comment by zunder** [comment]
@leebenson 
One downside of **not** using the import of these styles with `babel-plugin-import` is that the whole antd package is being included, resulting in a bigger bundle size.

**Comment by leebenson** [comment]
No prob, glad it helped.
