### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by nate0001** [reactql/kit#64]
With the recent support of enabling CORs options and the auth example, it would really be nice to be able to run the servers as HTTPS or HTTP. I see the getURL functions have the flag in there as well. Are there plans to build support for this?

**Comment by leebenson** [comment]
yep, it's on to my radar, especially with [experimental support for http/2](https://nodejs.org/api/http2.html) landing in the Node.js core.

I'm planning on adding a `config.enableSSL()` or similar function for adding a key/cert combo for auto-https in Koa in the coming days.

However, where possible, I'd recommend keeping SSL upstream, in Nginx or equivalent. A good load balancer/proxy is generally going to be more performant, offer better customisation, and give you a more mature solution for HTTP/2.

FWIW, running Nginx through Docker with ReactQL's `Dockerfile` as a proxied container is what I do in production.

**Comment by nate0001** [comment]
You can also use the http2 module. I was able to get the server portion running on http/2, but the browser wasn't. Would it matter if the browser portion wasn't?

My use case is AWS. Not sure how our traffic proxies are setup.

**Comment by leebenson** [comment]
> You can also use the http2 module

http/2 support in Node is experimental, and has a streaming interface for pushing data back and forth (opening up a few websocket-like interesting use cases). I definitely wouldn't recommend running anything in production on it yet.

In the meantime, I'll implement `https` for SSL.

> Would it matter if the browser portion wasn't?

It shouldn't. The browser bundle only communicates with the server over GraphQL, so it doesn't care what's running the server bundle.

> My use case is AWS

An EBS can be set-up to listen/respond to HTTPS traffic, but use plain HTTP as a back-end listener (on any port), so you can already implement HTTPS for front-facing traffic this way.

With that said, if you want end-to-end encryption (i.e. ensuring traffic between EBS and your ReactQL server is also encrypted), then I'd recommend SSL be co-located with your Node server - either as a Nginx proxy that's running on the same server/via Docker, or directly implementing the `https` module in your ReactQL project.

Once `config.enableSSL()` is implemented, the latter will be super easy to do.

**Comment by leebenson** [comment]
Released in [2.6.0](https://github.com/reactql/kit/releases/tag/2.6.0). `npm i -g reactql` to upgrade.
