### ISSUE TITLE
method to change app.context

### ISSUE THREAD

**Issue by reactgoo** [reactql/kit#65]
Koa has option to change app.context (the prototype from which ctx is created from). Could we have a method to do that without modifying "kit" folder files?

**Comment by leebenson** [comment]
I've got 'general purpose `app` middleware' on my to-do list, for manipulating the Koa `app` instance directly, which would make this possible. Will update this issue when released.

**Comment by leebenson** [comment]
Released in [2.6.0](https://github.com/reactql/kit/releases/tag/2.6.0). `npm i -g reactql` to upgrade.
