### ISSUE TITLE
isomorphic cookies

### ISSUE THREAD

**Issue by reactgoo** [reactql/kit#67]
Is there any workaround to get cookies from React component when SSR?

**Comment by leebenson** [comment]
Check out https://github.com/reactql/examples/tree/master/auth

It uses cookies on the server, and stores the same data as JWT on the client. The effect is essentially universal cookies; both environments can access the same data.

Alternatively, when you're setting cookies, you can pass the `{ httpOnly: false}` flag on the call to `ctx.cookies.set()` call (like [here](https://github.com/reactql/examples/blob/master/auth/src/graphql/session.js#L83-L86)), to make the cookie available programatically via JS.

I'll close this issue now, but if that doesn't answer your question, feel free to comment.
