### ISSUE TITLE
graphql endpoint uri in production

### ISSUE THREAD

**Issue by reactgoo** [reactql/kit#71]
I made project with default kit files -> npm run build -> npm run server

When I visit page at mydomain.com all graphql queries from client go to "http://localhost/graphql" 

I can fix this by setting "defaultHost" to my mydomain.com in env.js. Is it proper behavior?

**Comment by ralexandr** [comment]
I have the same problem. Is there any proper way to set host for production (with nginx as a web-proxy) without changing kit's files?

**Comment by leebenson** [comment]
Setting `SERVER_DEV_HOST` and `SERVER_PROD_HOST` is _supposed_ to update the endpoints in each environment, but I'm running into issues locally too.

I'll refactor `kit/lib/env` today to work as expected.
