### ISSUE TITLE
can't provide jQuery

### ISSUE THREAD

**Issue by corpz** [reactql/kit#74]
Maybe I don't understand this webpack config properly, but I can't provide jQuery globally

I put ProvidePlugin where I can, but it does not work for me 
```
new webpack.ProvidePlugin({
       'window.Tether': 'tether',
       $: 'jquery',
       jQuery: 'jquery'
}),
```

**Comment by leebenson** [comment]
I'll explore this in the next release

**Comment by xtools-at** [comment]
@corpz works fine for me, in kit/webpack/browser.js, I've added
```
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
    }),
```

to the _plugins_-array.
