### ISSUE TITLE
Maintain state on refresh

### ISSUE THREAD

**Issue by nate0001** [reactql/kit#75]
It would be cool to extend state rehydration to browser refresh. I think this is done using localStorage so a package like store2?

**Comment by leebenson** [comment]
This could probably be handled with redux middleware. I'll add a config function so this can be set in userland, in the next release

**Comment by wmhafiz** [comment]
Definitely will be a handy feature! Looking forward to it!

**Comment by leebenson** [comment]
I'll close this for now, since I'm tracking in https://github.com/reactql/kit/issues/80#issuecomment-332441041
