### ISSUE TITLE
Theming through less.modifyVars

### ISSUE THREAD

**Issue by zunder** [reactql/kit#76]
I am trying to apply theming through less by modifying the variables in order to load a certain set variables contained in a `@{theme}.global.less` file:

```less
// styles.global.less

@theme: default;
@import "./themes/@{theme}.global.less";
```

```js
// themes.js

const less = require('less')

export const switchTheme = (theme) => {
    switch (theme) {
        case 'dark':
            less.modifyVars({
                '@theme': 'dark'
            })
            less.refreshStyles()
        ...
    }
}
```

For some reason calling `switchTheme('dark')` does not do anything here. I am wondering if it is completely less specific or if the issue is known in this kit.

**Comment by leebenson** [comment]
Less is being transformed to CSS statically via Webpack. By the time you're using less in userland, the resulting CSS has already been built and `styles.css` is already in the browser with the original `@theme`, so AFAIK that's outside of the realm of programmatic access.

I don't use Less personally so there may be some way that the `less-loader` is able to sync with userland code, but I'm not aware of how that'd work.

Feel free to post here if you figure out a solution that requires a Webpack change, and I'll happily incorporate that in the main kit.

**Comment by zunder** [comment]
@leebenson Thanks, that makes sense.

Regardless of less, how do you manage the theming requirement using this kit?

**Comment by leebenson** [comment]
@zunder - I'm not exactly sure what you mean by 'theming requirement', but ALL css of any kind - whether it be plain CSS, SASS or LESS - is done in userland at `src/app.js`.

So it's entirely up to you how you lay it out.

For example, you could have two classes like:

```css
.class1 {
    color: blue;
}
.class2 {
    color: red;
}
```

... and then import them:

```js
import css from './styles.css';
```

... and then choose which class you want dynamically inside a React component:

```js
<h1 className{someProp ? css.class1 : css.class2}/>
```
