### ISSUE TITLE
Heroku SSL $PORT timeout

### ISSUE THREAD

**Issue by edolyne** [reactql/kit#78]
I'm currently running `v2.8.5` and I'm running into and issue with SSL on a free Heroku dyno.

Leaving the app settings as is the app runs the `graphql` server via http which loads the entry page without issue, however when navigating to a new route the route is blank as it won't allow mixed content to be loaded.

I've attempted to fix this by trying two different changes in my app settings:

`config.disableHTTP();` and `config.forceSSL({ trustProtoHeader: true });`

I've tried both of these separately as well as together and each time I've had this error:

`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`

I'm wondering if anyone else has run into this and has found a solution. Thanks.

**Comment by leebenson** [comment]
Per [these lines](https://github.com/reactql/kit/blob/master/kit/entry/server.js#L399-L404) in `kit/entry/server.js`, ReactQL looks for an environment var named `SSL_PORT` to bind an HTTPS server.

Have you tried running with `SSL_PORT=$PORT` in the Heroku command line?

**Comment by edolyne** [comment]
@leebenson I do have the SSL_PORT set, but it's still calling a http graphql server.

**Comment by lookagit** [comment]
It looks like  build take more than 60seconds and and therefore throws out an error
https://devcenter.heroku.com/articles/dynos#web-dynos
When I restart aplication several times app is up and running , although graphql does not work yet
on  the client side
![rsz_screenshot_from_2017-09-16_23-38-53](https://user-images.githubusercontent.com/17603638/30516229-d53d41da-9b38-11e7-94bc-9789ef1afe74.png)
![rsz_screenshot_from_2017-09-16_23-38-45](https://user-images.githubusercontent.com/17603638/30516230-d812ff44-9b38-11e7-9731-f7159053838d.png)

When I go on
someapp.heroku/graphql everything works good

**Comment by leebenson** [comment]
good catch @lookagit.

I'm working on some performance optimisations that should lead to quicker builds overall, but a better longer-term solution to this would be to pre-build using the Docker image instead (which Heroku supports as a deployment style.)

Running the Docker image and attaching to `$PORT` will only take 1-2 seconds, because the distribution bundle will have been built before it's pushed.

There's a `Dockerfile` in the project to support this - try that and let me know how you get on.

**Comment by lookagit** [comment]
i hardcoded in 
export function browserClient() {
  return createClient({
    networkInterface: getNetworkInterface('https://bar-soft.herokuapp.com/graphql'),
  });
}
and my graphql is live finally :D

**Comment by lookagit** [comment]
"start": "npm run server"   
"postinstall": "npm run build", === MAGIC

https://help.heroku.com/P1AVPANS/why-is-my-node-js-app-crashing-with-an-r10-error
