### ISSUE TITLE
Make app.use(koaHelmet()) optional

### ISSUE THREAD

**Issue by ralexandr** [reactql/kit#79]
Hi! Could you please give the ability to turn off koaHelmet inside app.js (througn config instance) ?
I need to run reactql bundle in an environment where headers are read-only and koaHelmet can't work properly in such situation. 
I will be very handy if there will be a method (smth like **config.disableKoaHelmet**) for managing koaHelmet (like it is already done for bodyParser).

**Comment by leebenson** [comment]
good idea - I'll add that to the next release.
