### ISSUE TITLE
Apollo 2.0 - roadmap/feedback

### ISSUE THREAD

**Issue by leebenson** [reactql/kit#80]
With [Apollo 2.0 now in beta](https://dev-blog.apollodata.com/whats-coming-in-apollo-client-2-0-bcd8ea64acbd) now available, a ReactQL bump to the latest Apollo client is just around the corner.

As well as being smaller and more nimble, v2 will also be modular - removing the implicit Redux store and `createNetworkInterface()`, and replacing them with a (eventual) plethora of explicit caching and networking middleware that can be swapped out to do things not currently possible in Apollo v1.

This opens up some interesting options for the next major release of ReactQL. This could be as trivial as swapping out the current client for v2, and keeping everything else exactly the same - e.g. Redux for app state management, SSR and store (de|re)hydration, exactly the same pipeline - and enjoying smaller bundle sizes, and more performant client-side caching.

Or it could be something more elaborate/interesting, including:

----

- Dropping Redux entirely, and letting Apollo handle full app state entirely within GraphQL. Instead of an explicit `addCounter()` reducer, why not keep our _entire_ app in GraphQL and simply run a mutation, letting Apollo handle caching and state management without a separate Redux `@connect` decorator?

- Subscriptions. We could ditch HTTP, and opt for server-pushed data via websockets by default, extending the Observable pattern Apollo 2's `Link` interfaces introduce and keep the browser + server in sync -- making it trivial (or at least easier) to respond to server-side data cursors, push new DB records down the wire, etc.

- Universal session caching. [There's interest](https://github.com/reactql/kit/issues/75) in maintaining state between browser refreshes, but what about between _server_ refreshes? Using a distributed store (Redis, etc) and extending Apollo 2's new `apollo-cache-core`, ReactQL could implement session-based storage using JWT so that SSR always reflects the very latest data, regardless of whether queries are invoked in the browser or on the server -- with eventual consistency, custom TTLs and fine cache control.

- Session + global real-time updates. With ws + universal caching, 'real-time' is basically solved. Certain mutations/subscriptions could be marked as 'global' and pushed down to every connected client -- others would be session-specific, and pushed down to the active ID. This could also massively simplify user auth. No sessions, no stores, no reducers - just GraphQL. Hello true real-time apps?

----

These are just some early/immediate thoughts, and I've love to hear your feedback on any of the above features.

Is there any interest in adopting 'real-time by default'? Are you currently using ReactQL as a full-stack starter kit? Or do you prefer to handle the GraphQL server separately?

What features would you like to see ReactQL take care of?

On these, or any other Apollo v2 topics, I invite your thoughts.

**Comment by jbaxleyiii** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by mnpenner** [comment]
- Subscriptions + real-time updates by default sounds great
- Dropping Redux sounds nice. The fewer ways have to manage state the better, as long as the new way supports all the use-cases. In particular, I'm interested to know how you would handle form state without Redux? We wouldn't be able to use a library like Redux Form, which means we're back to square one again.
- Caching between browser and server refreshes doesn't appeal to me personally. If I'm refreshing the browser in an SPA it's because the app screwed up and I'm explicitly trying to clear the state.

**Comment by leebenson** [comment]
> Dropping Redux sounds nice. The fewer ways have to manage state the better, as long as the new way supports all the use-cases. In particular, I'm interested to know how you would handle form state without Redux? We wouldn't be able to use a library like Redux Form, which means we're back to square one again.

All state would be GraphQL. Just like in the recent [auth example](https://github.com/reactql/example-auth), filling out a form (be it an email/password login box, or a full-blown contact form) could be a mutation like this:

```graphql
mutation login($email: String, $password: String) {
  login(email: $email, password: $password) {
    ok
    errors {
      field
      message
    }
    jwt
    user {
      id
      email
      firstName
      lastName
    }
  }
}
```

In the above, we're passing an `email` and `password` from a form, and getting a fully-qualified `user` object back, along with errors in a `{ field, message }` format.

Something similar like this could be applied to forms - or indeed, any type of action - but instead of receiving a 'user', you could receive a response object of some kind that is cached/stored within Apollo and could be queried by any other React component simply by decorating it in `@graphql` from `react-apollo`, like we do with this `<User>` component per the example above:

```js
const User = props => {
  const user = (props.data && props.data.session && props.data.session.user) || {
    id: '',
    email: '',
    firstName: '',
    lastName: '',
  };
  const fields = [
    {
      name: 'id',
      label: 'User ID',
      value: user.id,
    },
    {
      name: 'email',
      label: 'E-mail',
      value: user.email,
    },
    {
      name: 'firstName',
      label: 'First name',
      value: user.firstName,
    },
    {
      name: 'lastName',
      label: 'Last name',
      value: user.lastName,
    },
  ];

  return (
    <Grid.Row>
      <Grid.Column>
        <Segment color="violet">
          <Header>Logged in details</Header>
          <p>
            This data is pulled back from the GraphQL server using the JWT token that&rsquo;s
            stored in <em>localStorage</em> or in the <em>jwt</em> cookie that&rsquo;s sent
            to the server. Custom middleware handle passing the JWT to our GraphQL request.
          </p>
          <Form>
            {fields.map(field => (
              <Form.Input
                readOnly
                key={field.name}
                name={field.name}
                label={field.label}
                value={field.value} />
            ))}
          </Form>
        </Segment>
      </Grid.Column>
    </Grid.Row>
  );
};

export default graphql(sessionQuery)(User);
```

In this case, we're populating form fields with the `user` object we returned from a mutation fired from an unrelated component - in much the same way an unrelated Redux reducer can lead to other components re-rendering when the underlying state changes.

It's exactly the same concept, except it all stays within GraphQL rather than relying _another_ store management layer on top.

Benefits are then:

* Reduced bundle size - you can ditch Redux, or third-parties like MobX.
* Reduced boilerplate. No need to specify reducers/actions/state listeners - you can keep everything in GraphQL.
* The full flexibility/expressiveness of GraphQL. If you store state locally, you can define the state ahead of time as a regular GraphQL schema and query it per the full power of GraphQL -- with type safety, nested relationships, superior null handling, etc.

Since Apollo 2.0 ditches Redux, we might as well embrace the freedom of unshackling from third-party store management, while treating GraphQL as a common query language across our entire app.

> Caching between browser and server refreshes doesn't appeal to me personally. If I'm refreshing the browser in an SPA it's because the app screwed up and I'm explicitly trying to clear the state.

I'm thinking more in terms of 'classic' session handling. In a traditional web app, if you log into a user's dashboard and click around, then hit refresh, the expectation is you're refreshing against an authenticated page.

Currently, unless there's some way the browser is passing a JWT to the server (like I did in the [auth example project](https://github.com/reactql/example-auth)), hitting refresh would actually _kill_ the state, which would include that user's details, any 'state' that may affect how UI is laid out, any temporary variables that may have been stored in state to act as a scratchpad to what the user was doing on the page, etc.

IMO, the advantage of having state changes mirrored on the server and stored against a JWT identifying the user, is better aligned with what a 'session' traditionally means to a user -- i.e. whatever they do won't be lost when they exit, so long as they're part of that same 'session' .

Of course, what 'session' means is up to the developer. It'd still be possible to kill all state by simply terminating the session (by any mechanism.) This could mean hitting 'log out', clicking a 'reset' button, or simply a session timing out/being killed automatically when the browser exits. There would be an API for configuring TTL, terminating on demand, etc.

The point here is more about enabling the possibility to fully expand upon two-way subscriptions, rather than enforcing 'always sticky, all the time'.

This area definitely needs more thought (and quite a bit of code), but could lead to some very interesting scenarios that are not easily answered by other tooling... i.e. creating real-time, universally rendered apps there 'state' is accessible by both the server and the browser, and (nearly) always in sync.

Coupled with a 'GraphQL all the things' approach, this could be completely change the approach to building fast, real-time web apps, that still benefit from native SSR.

Sort of Meteor meets old ASP.net view state - but with GraphQL being the common language, and sessions being held on a distributed back-end. Or something like that.

**Comment by mnpenner** [comment]
I'm still not certain how forms would work with GraphQL. Would every keypress fire a mutation? Because that's effectively what we're doing now -- either moving the current input into the component's state or Redux's store. Isn't that a big chunk of overhead per keypress? Loading and saving is of course fine to do with GraphQL.

> I'm thinking more in terms of 'classic' session handling. In a traditional web app, if you log into a user's dashboard and click around, then hit refresh, the expectation is you're refreshing against an authenticated page.

Well of course I wouldn't expect to be logged out if I press refresh 😄 I guess having the *option* to store additional data other than just authentication would be nice. I suppose that could provide for some nice opportunities, like 'recovering' what the user has worked on if they accidentally close a tab or their browser crashes or whatever.

**Comment by leebenson** [comment]
> I'm still not certain how forms would work with GraphQL. Would every keypress fire a mutation? Because that's effectively what we're doing now -- either moving the current input into the component's state or Redux's store. Isn't that a big chunk of overhead per keypress? Loading and saving is of course fine to do with GraphQL.

Not necessarily. You could use React's local `state` for ephemeral data, and then fire the mutation `onSubmit`. Unless other components require access to every keystroke, firing a Redux reducer `onKeyPress` is probably overkill, anyway.

GraphQL mutations aren't necessarily any more expensive than the equivalent reducer in Redux, when used locally. We're talking 1-2ms of overhead.

> Well of course I wouldn't expect to be logged out if I press refresh 😄 I guess having the option to store additional data other than just authentication would be nice. I suppose that could provide for some nice opportunities, like 'recovering' what the user has worked on if they accidentally close a tab or their browser crashes or whatever.

Yup. The idea would be that you can save _all_ state, not just auth data. So if you've clicked a button that disables a component, it will _still_ be disabled if you hit refresh. Syncing state is generally a difficult thing to do, and more often than not we don't want an accidental refresh to cause chaos in the app. This paradigm makes the default behaviour sensible -- i.e. simply pick up where you left off -- meaning you're in control of explicitly resetting state within your UI or by terminating the session via TTL or explicitly.

**Comment by mnpenner** [comment]
I've found it necessary to put form state into redux. It's too much work to
bubble up the state from deeply nested subcomponents. It also makes
validation much easier if you have access to everything. And state isn't
lost it you show/hide the form. And sometimes you do want to respond to
form changes in real-time from other components.

I'll guess I'll have to dig into this deeper and see how feasible it is to
build a form library around graphql.

**Comment by nate0001** [comment]
I wouldn't get rid of redux. Many people will still want to use redux (and storing into local graphql is a big shift). There's also the case if you are connecting to an external graphql server that you have no control over. So you would have to use redux anyway.

**Comment by leebenson** [comment]
@nate0001 - I'm exploring a more modular approach to ReactQL, that would allow you to progressively add features to the stack - including Redux. You'd also be able to do this in userland in exactly the same way as it's currently done-- it would just stop being a hard requirement.

I'm not sure what you mean by external GraphQL servers and Redux. All a GraphQL server does is receive queries, and respond back in a JSON format. Stores/state management is something that happens on the client exclusively. Apollo v2.0 takes care of caching/storing the returned data without Redux.

**Comment by nate0001** [comment]
@leebenson - I really like the idea of the modular approach and it's the main reason why I've chosen to use this kit over others (nextjs, create-react-app, etc) for a project at work.

What I meant by external GraphQL server is that the above scenario depends on you running a local (in process) GraphQL server. However, some people won't always have that luxury. For instance, the project I'm working on is using an external GraphQL server (pointed to http://some.url.to.a.graphql.server). Apollo doesn't allow connecting to multiple GraphQL servers. So in this instance, there would be no way you could store state in GraphQL.

**Comment by leebenson** [comment]
@nate0001 - understood. I'm working on a new framework that will make it very easy to swap out pieces of ReactQL. So if you want to build a monolithic app with GraphQL running on Node - and you want all the goodies like built-in session handling, JWT auth, etc - that'll be a case of dropping in just one preset.

If you want to connect to a third-party server and build client-side code statically, just swap it out for another.

There will be a bunch of 'official' presets, and making your own (or extending an existing one) will be super simple.

Hoping to get the first version out for it this week.

**Comment by gihrig** [comment]
> Hoping to get the first version out for it this week.

I'm in favor of all options you have discussed. Starting with a more modular architecture and adding features as they become available.

> Session + global real-time updates. With ws + universal caching, 'real-time' is basically solved. 

Woot! exciting times ahead ✨ 💖 ✨

**Comment by nate0001** [comment]
@leebenson will you be upgrading redux-persist to v5? It's a major API change

**Comment by NiluK** [comment]
I'm happy with dropping with redux as long as there is a decent migration guide for it. Unfortuantely, a lot of our projects depend on actions and reducers so losing redux without ability to add support in userland would seriously hinder our progress. So long as userland redux is fully supported, I am in favour of dropping redux - no need to add unused dependencies.

**Comment by leebenson** [comment]
> @leebenson will you be upgrading redux-persist to v5? It's a major API change

We're not currently using `react-persist`, so it wouldn't be an upgrade, but rather an introduction. What's probably best is an API that allows you to orchestrate the Redux middleware stack in userland rather than editing `kit/lib/redux.js` directly, then you can throw in whatever you like.

> I'm in favor of all options you have discussed. Starting with a more modular architecture and adding features as they become available.

I've been playing around with a few approaches. My initial goal was to release something that would look something like this:

```js
const app = require('reactql/app')
const setup = ['css','images','reactql'].map(what => require(`reactql/${what}`).setup())

app.webpack(setup).entry('./your/entrypoint.js').launch()
```

Those three lines would be all you'd need to bootstrap an app. The `setup` line is middleware - each package being able to modify the main Webpack config, and effect changes at the entry point.

`launch()` would build the app per the Webpack config, using the entrypoint, and would build a distribution bundle for each environment defined in Webpack.

I had some preliminary code that I got working quite well, in limited scenarios. The issue with that approach is that, often, mapping Webpack middleware isn't linear. ReactQL's current config is spread over [10 files](https://github.com/reactql/kit/tree/master/kit/webpack), with multiple options that overlap, and edge cases that are resolved outside of [webpack-config](https://github.com/Fitbit/webpack-config)'s merge capabilities. Getting something to work would mean overhauling the approach I'm currently taking with Webpack.

This is compounded when supporting multiple environments. My initial goal was to have middleware for supporting browser, SSR, and static bundling separately, so that pieces could be dropped entirely. But again, that quickly gets us back into territory where each middleware in the stack has to then be 'environment aware' and make allowances/exceptions. The API for this wasn't as clean as I liked, and it became obvious fast that I'd essentially be creating a project that diverged quite a lot from ReactQL's primary raison d'être.

So, all that to say, that I'm still not quite settled on the modular approach yet. 'Modular' in this context means being able to dynamically add to Webpack config based on packages, as well as affect the runtime of the entrypoint to the app. I'll give this some more thought later down the road, and may even spin this off into a separate framework that puts Webpack front and centre, but I'm currently a little too busy to tackle that right now.

Instead, what I'll likely do for the next major release of ReactQL is:

1. Bump to Apollo v2, and allow userland middleware/config
2. Make it trivial to add Redux middleware to the mix

Sticky/distributed sessions, etc, may come later, or may just wind up being an example kit. Not sure yet.

There's still a few things that need to happen in Apollo 2 before I tackle the above. For example, we're using [apollo-local-query](https://github.com/af/apollo-local-query) via SSR to render 'local' schema rather than hitting the network, which currently relies on v1's `createNetworkInterface`. I'm not sure whether there's a ready equivalent for v2. Might need to wait for the ecosystem to mature a bit before making the switch.

**Comment by nate0001** [comment]
My bad. Looks like i've got some packages installed that I never removed. 😆

**Comment by leebenson** [comment]
@jbaxleyiii - what's the recommended approach for a 2.0 equivalent of https://github.com/af/apollo-local-query?

We currently use this for SSR, to avoid the HTTP hop when React rendering and GraphQL are part of the same local node.

It seems that it should be fairly trivial to make work for 2.0, but if there are any ready-made packages or code examples floating about, that would help us get ReactQL transitioned over to the new release?

Appreciated!

**Comment by timLoewel** [comment]
If redux is removed, what is the substitute for the side effect libraries like redux-sagas or redux-epics? Many of their use cases (data fetching..) would be replaced. But there is still the need to have some side effects that tie into the store (e.g. wait for camera to take photo -> process photo -> store in database). How does this work with apollo 2.0?

**Comment by mergebandit** [comment]
At some point, jbaxleyiii will ship [apollo-link-state](https://www.npmjs.com/package/apollo-link-state), and an `apollo-link-rest` was demo'd at graphql-summit in SF end of October. You'll be able to "stitch" together client-side schemas using composed links, which will allow you to use graphql as the single source of truth for all data - while still exposing the ability to drop redux in as your backing cache if necessary.

**Comment by fhollste** [comment]
[Here's a good article about how and why to make the shift from Redux to Apollo 2.0
](https://dev-blog.apollodata.com/the-future-of-state-management-dd410864cae2)

Any updates on a ReactQL kit with Apollo 2.0 and/or migration docs?

**Comment by leebenson** [comment]
Thanks for sharing, @fhollste.

ReactQL is being split into two projects:

1. **Launch.js**, a general-purpose Webpack bundler, with pluggable configs that can be added to it.

2. **A ReactQL plugin** for Launch.js, with separate plugins for CSS and other, more 'opinionated' pieces of ReactQL.

Both are written in Typescript, but usable as vanilla JS.

I'm [making headway](https://github.com/launchjs) with the new stack, and I'm hoping to have a first release early in the new year (as I've mentioned elsewhere, I have personal projects that are blocking on it, so it's being worked on as a priority.)

The first iteration will be vanilla, universal React, followed by a thunk'd variant which will layer Apollo 2 on top.

(For existing users that are happy with Apollo v1 + Redux, that would be easy to augment manually on top of the React plugin.)

I'm getting there...

**Comment by leebenson** [comment]
FWIW, the new syntax will look something like this:

```js
import app from "@launchjs/app";
import reactql from "@launchjs/reactql";
import css from "@launchjs/css";

// Add in the plugins
app.add(reactql, css);

/* Configure the plugins */

// ReactQL
reactql.setBrowserMain('path/to/main.ts'); <-- should export a function that takes a `browserConfig`
reactql.setServerMain('path/to/main.ts'); <-- the same, but `serverConfig`

// CSS
css.setOutputFilename('styles.css'); // <-- A plugin usually has options like this..

/* Build/launch the app - by default, in development mode */
app.launch();
```

Then in your `main.(ts|js)` entry point, you'd so something like this:

```ts
// For use with `reactql.setServerMain`...
export default function(config: ReactQL.ServerConfig) {

// All the usual stuff you can currently do in ReactQL, but this time, typesafe!
config.addRoute(HttpMethod.GET, "/path", routeHandler);

// Export a main React component
config.setMain(MainComponent);
}
```

**Comment by leebenson** [comment]
Finally, since everything can be added as an NPM package, the CLI will be retired, and upgrading will be done with standard `npm i` tooling.

It'll move ReactQL from being a starter kit, to a very pluggable  / customisation framework.

**Comment by wmhafiz** [comment]
Looks great, can't wait to try it out !

**Comment by biels** [comment]
I'm currently using the client side of reactql 4.9.5 with my own graphql server. I would really appreciate the shift to Apollo Client 2.0 and even more if it comes in a modular way. The idea of going WebSockets by default is also nice, and with apollo link it will not be hard to also provide http as a fallback.
Looking forward to it!

**Comment by TreTuna** [comment]
I'm honestly stoked to see where this goes right now. I am in the camp of modularity and ripping Redux out with Apollo 2.0. I have a project right now where this repo without Redux and all the less/sass stuff (we're going to be using styled-components) would have been my prime setup. Any word on the progress with that? Looked at the repo and looks like progress stopped a little over a month ago.

**Comment by mnpenner** [comment]
@TreTuna After having looked into it some more, local state with Apollo 2 actually looks [quite tedious](https://youtu.be/2RvRcnD8wHY). I especially don't like having to markup the queries with `@client` everywhere. Not sure why local queries can't just be intercepted. The schema should know what goes where.

Also, [apollo-link-state](https://github.com/apollographql/apollo-link-state) still isn't stable so I wouldn't recommend ReactQL to incorporate it.

**Comment by leebenson** [comment]
Update on this thread: https://github.com/reactql/kit/issues/147#issuecomment-378173217

**Comment by leebenson** [comment]
A taste of what's to come a la [Launch.js](https://github.com/launchjs/app) presets:

https://github.com/launchjs/styles

I'm currently working on the new ReactQL preset (today, actually), which will make including it in your project as simple as it is to now include styles.

This approach also means we can drop a lot of the assumptions that come with the current version of ReactQL around styling, image bundling, compression, etc. All of those can be presets that can be chosen by the user rather than bundled as standard.

More updates soon!

**Comment by leebenson** [comment]
Closing per https://github.com/leebenson/reactql/releases/tag/3.0.0
