### ISSUE TITLE
how to configure with jest

### ISSUE THREAD

**Issue by caedmon** [reactql/kit#81]
I see jest in package.json but it seems there's a bit more config needed to be able to use it to test React components.  Any plans to add that either in kit or an example?

**Comment by nate0001** [comment]
What do you mean there's a bit more config needed?

I've got jest tests working without any additional config or setup.

**Comment by caedmon** [comment]
@nate0001 I did install react-test-renderer@next but still can't get it to work.  

I get 'Unexpected token' on the JSX.  Missing babel config?
And eslint doesn't recognize test, describe, it, expect.  Missing eslint config?

**Comment by nate0001** [comment]
I see what you mean. I had to install `eslint-plugin-jest`. Add `jest/globals: true` to `env` and add `jest` to `plugins` in `.eslintrc.js`.

The `Unexpected token` is caused by not importing React.

**Comment by nate0001** [comment]
Sorry there was some more. I submitted a PR.
