### ISSUE TITLE
browser_prod: background-image in stylesheets rise a error

### ISSUE THREAD

**Issue by DrReMain** [reactql/kit#86]
ERROR in ./src/views/Home/index.css
    Module build failed: ModuleBuildError: Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
      Reason: image not found

**Comment by DrReMain** [comment]
Because of  image-webpack-loader!!!
I solved this on OSX: https://www.npmjs.com/package/image-webpack-loader#libpng-issues

But it still have problem on win10

**Comment by leebenson** [comment]
You're probably best submitting an issue on image-webpack-loader, since image compression is something that's handled externally.
