### ISSUE TITLE
Problems accessing assets in production in a tunneled environment

### ISSUE THREAD

**Issue by nate0001** [reactql/kit#91]
Running this in an AWS environment that gets hosts rerouted with paths.

IE my server is accessible from `our-aws-environment.com/my-app`.

The problem I'm having is that the app is requesting vendor, manifest, style, etc from `our-aws-environment.com/manifest` (which results in a 404). This should be `our-aws-environment.com/my-app/manifest` (which are accessible) instead.

Having trouble trying to get this to work.

**Comment by leebenson** [comment]
You can use [react-helmet](https://github.com/nfl/react-helmet) (installed by default) to set a `<base target="_blank" href="http://our-aws-environment.com/my-app/" />` tag.

**Comment by nate0001** [comment]
What file would I do this in?

Got an example?

**Comment by leebenson** [comment]
Use it in any React component where you want to affect the `<head>` output.

For example:

https://github.com/reactql/kit/blob/master/src/components/main/index.js#L68-L73

**Comment by nate0001** [comment]
This doesn't work. The stylesheet, manifest, browser sources are using absolute paths `/assets/css/style`, `/manifest`, and `/browser`. The `<base>` header tag only works with relative paths.

See https://webdesign.tutsplus.com/articles/quick-tip-set-relative-urls-with-the-base-tag--cms-21399

**Comment by leebenson** [comment]
Automatic handling of `<base>` has been added as of [2.9.0](https://github.com/reactql/kit/releases/tag/2.9.0), which can be overridden by simply adding your own base tag inside of Helmet, like so:

```jsx
<Helmet>
  <base href="/some-new-path/" />
</Helmet>
```
